### ISSUE TITLE
Automatic Redirection

### ISSUE THREAD

**Issue by kamilmirza** [Magisk-Modules-Repo/dnscrypt-proxy2#1]
can you please add Automatic Redirection in this module 
like it used to in the previous versions by bluemeda
Automatic Redirection redirects all requests to dns-crypt without user interaction (no configuration required)

**Comment by lindroidux** [comment]
It is work in progress. A very flexible way is being implemented.

**Comment by mundocryptos** [comment]
> It is work in progress. A very flexible way is being implemented.
> Alternatively, copy the script file to /data/adb/service.d/

Any news on bringing back the automatic redirection? I uninstalled the bluemeda's version to install the revived one through Magisk and now I can't use it, nor through AfWall nor with an external script, because my custom ROM (LineageOS 14.1) doesn't have init.d. I tried the init.d injector module from Magisk repo, but doesn't do it. Why the bluemeda's version worked? What is the difference between a script and the way bluemeda used to redirect automatically?

**Comment by lindroidux** [comment]
There are no present plan to incorporate automatic redirection. A nice implementation is available at https://github.com/adit/dnscrypt-proxy/

**Comment by lindroidux** [comment]
Alternatives are available at

- https://git.nixnet.xyz/quindecim/dnscrypt-proxy-android with support at https://t.me/qd_invitation
- https://github.com/CHEF-KOCH/dnscrypt-proxy-android
- https://github.com/adit/dnscrypt-proxy/

**Comment by lindroidux** [comment]
Init.d is not required for ROM having magisk installed. Scripts in /data/adb/service.d/ will be auto-started by magisk.
