### ISSUE TITLE
forwarding-rules didn't work properly

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/dnscrypt-proxy2#5]
With this provided iptables rule :
`$IPTABLES  -t nat -A OUTPUT -p tcp ! -d 1.1.1.1 --dport 53 -j DNAT --to-destination 127.0.0.1:5354
$IPTABLES  -t nat -A OUTPUT -p udp ! -d 1.1.1.1 --dport 53 -j DNAT --to-destination 127.0.0.1:5354`

And some forwarding-rules are deffrent from fallback  dns server address :
`google.com  8.8.8.8`

dnscrypt-proxy would forward this request to 8.8.8.8, then redirected by iptables back to dnscrypt-proxy  , until maximum number of simultaneous client connections and got drop. 

Is there anyway to resolve this problem?

**Comment by lindroidux** [comment]
Pls elaborate your question

**Comment by hineH** [comment]
[This](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Forwarding)  feature of dnscrypt-proxy didn't work properly because iptables is unable to identify the dnscypt-proxy forwarded request separated from normal dns request(should be redirected to dnscrypt-proxy). So is there anyway (such as run dnscrypt-proxy as a specific user and match --uid-owner in iptables rule ?) to avoid dnscrypt-proxy forwarded request get redirected?

**Comment by lindroidux** [comment]
Yes, it may be possible but I am not an expert in iptables. Pls refer the afwall wiki for similar examples.

**Comment by hineH** [comment]
@lindroidux  I solved this problem.

Firstly I tried to use " su {uid} -c COMMAND" to run as a spacific user, but there are some puzzling permission problem (unable to read the directory and unable to bind socket) I can't solved. Therefore , I tried to use a real user(an application) to run it. Finally, it worked fine.

The following is what I did:

1. Comment all lines in `/data/adb/modules/dnscrypt-proxy2/service.sh` to prevent dnscrypt-proxy starting normally.

2. Edit `/data/adb/service.d/dns-redirect.sh`,replace the redirection rules:
```sh
$IPTABLES  -t nat -I OUTPUT -m owner ! --uid-owner 10160 -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:5354
$IPTABLES  -t nat -I OUTPUT -m owner ! --uid-owner 10160 -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:5354
```
The `10160` is the specific application's uid , (for me I used termux or tasker)

And add these rules to prevent requests leaking through ipv6:
```sh
$IP6TABLES -I OUTPUT -p udp --dport 53 -j REJECT
$IP6TABLES -I OUTPUT -p tcp --dport 53 -j REJECT
```
3. Add the `/storage/emulated/0/dnscrypt-proxy/service.sh`:
```sh
#!/system/bin/sh
while ! [ `pgrep -x dnscrypt-proxy` ] ; do
		/system/bin/dnscrypt-proxy -config  /storage/emulated/0/dnscrypt-proxy/dnscrypt-proxy.toml && sleep 15;
	done
```
4. Edit `/storage/emulated/0/dnscrypt-proxy/dnscrypt-proxy.toml`, replace `/data/media/0/` by `/storage/emulated/0/` in all the path configurations in this file otherwise there would be some permission problems.

5. Use tasker or any other application running this shell command on boot:
```sh
/system/bin/sh /storage/emulated/0/dnscrypt-proxy/service.sh
```
6. Now it's OK to use any fallback and forwarding addresses in dnscrypt-proxy, and there are no request leaking even some program explicitly query to any dns server.

Write a simple apk could do the whole process automatically.

**Comment by lindroidux** [comment]
fallback resolvers are used only for downloading/caching the public-resolvers.md.
